#Note that for the upload command to work, the AWS access key and the AWS
# secret key must supplied as environment variables call AWS_ACCESS_KEY and
# AWS_SECRET_KEY
#
# Example invocation:

#     docker build --no-cache -f Dockerfile.processgff -t test-gff . 
#     docker run --rm -e "AWS_ACCESS_KEY=<AWSACCESS>" -e "AWS_SECRET_KEY=<AWSSECRET>" test-gff

# The script "simple-command.sh" is also allows specifying what S3 bucket to use
# via an environment variable called AWS_S3_BUCKET but the default is agrjbrowse, the
# Alliance bucket for jbrowse data.  It also assumes the path is /mod-jbrowses/zfin,
# which is what the trackList.json (JBrowse's track config file) assumes as well. 
# So, if you want to use a different bucket or path, it needs to be changed both in the
# simple-command.sh script as well as in /jbrowse/data/trackList.json file (basically,
# all of the urlTemplate entries for NCList tracks).

# Obviously the simple-command.sh processing script could and probably should be
# generalized to use a config file to control what gets processed, but since
# the zfin JBrowse instance is currently pretty simple, there isn't much need to do that.

# Also note that this image only processes GFF files into NCList json and does
# not deal with processing FASTA data (since it changes relatively infrequently,
# that is the sort of thing that ought to be done "by hand").  It also doesn't deal
# with any other file times like BigWig or VCF.

FROM gmod/jbrowse-gff-base:latest 

LABEL maintainer="scott@scottcain.net"

RUN git clone --single-branch --branch main https://github.com/alliance-genome/agr_jbrowse_zfin.git
RUN git clone --single-branch --branch master https://github.com/alliance-genome/agr_jbrowse_config.git

RUN cp /agr_jbrowse_zfin/simple-command.sh / && \
    cp /agr_jbrowse_zfin/parallel.sh / && \
    mkdir -p /jbrowse/data/seq && \
    cp /agr_jbrowse_zfin/jbrowse/data/GRCz11/seq/refSeqs.json /jbrowse/data/seq


VOLUME /data
#ENTRYPOINT ["/bin/bash", "/simple-command.sh"]
ENTRYPOINT ["/bin/bash", "/parallel.sh"]
